create or replace 
PROCEDURE GET_MONTH_BREAK_DOWN 
(
  MONTH IN NUMBER  
, YEAR IN NUMBER 
, RESULT OUT SYS_REFCURSOR
) AS 


BEGIN
   
  OPEN RESULT FOR
  SELECT CA.TYPE, M.NAME META_CATEGORY,CA.NAME CATEGORY,SUM(T.AMOUNT) AMOUNT
  FROM CATEGORY CA, META_CATEGORY M, TRANSACTION T
  WHERE M.ID = ca.meta_category_id
  AND CA.ID = t.category_id
  AND extract(MONTH FROM t.transaction_date) = MONTH
  AND extract(YEAR FROM t.transaction_date) = YEAR
  AND M.ID <> 25
  GROUP BY CA.TYPE,M.NAME,CA.NAME
  ORDER BY CA.TYPE,M.NAME,CA.NAME;
  
END GET_MONTH_BREAK_DOWN;