create or replace 
PROCEDURE GET_YEAR_OVERVIEW 
(
  YEAR IN NUMBER,
  YEAR_OVERVIEW OUT SYS_REFCURSOR
) AS 

INCOME NUMBER(38,2);
EXPENSE NUMBER(38,2);
UNTRACKED NUMBER(38,2);
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_SUMMARY_TABLE';
  FOR MONTH IN 1..12 LOOP
    SELECT SUM(AMOUNT)
    INTO INCOME
    FROM TRANSACTION,CATEGORY
    WHERE TYPE = 'I'
    AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
    AND EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
    AND CATEGORY.ID = CATEGORY_ID
    AND META_CATEGORY_ID NOT IN (25,3068);
    
    SELECT SUM(AMOUNT)
    INTO EXPENSE
    FROM TRANSACTION,CATEGORY
    WHERE TYPE = 'E'
    AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
    AND EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
    AND CATEGORY.ID = CATEGORY_ID
    AND META_CATEGORY_ID NOT IN (25,3068);

    SELECT SUM(AMOUNT)
    INTO UNTRACKED
    FROM TRANSACTION,CATEGORY
    WHERE EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
    AND EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
    AND CATEGORY.ID = CATEGORY_ID
    AND META_CATEGORY_ID=3068;
    
    IF UNTRACKED > 0 THEN
      INCOME := INCOME + UNTRACKED;
      --FEB INCOME = 3550.65
      --MAR EXPENSE = 4029.56
    ELSIF UNTRACKED < 0 THEN 
      EXPENSE := EXPENSE + UNTRACKED;
    END IF;
    
    INSERT INTO TEMP_OVERVIEW VALUES (MONTH,INCOME,EXPENSE);
    COMMIT;
  END LOOP; 
  
  OPEN YEAR_OVERVIEW FOR
  SELECT * FROM TEMP_OVERVIEW ORDER BY MONTH;
  
END GET_YEAR_OVERVIEW;