create or replace 
PROCEDURE GET_SUMMARY 
(
  MONTH IN NUMBER  
, YEAR IN VARCHAR2  
, SUMMARY_RESULT OUT SYS_REFCURSOR  
) AS 
BEGIN
  OPEN SUMMARY_RESULT FOR
  SELECT 'PRIOR CASH ACTIVITY' DESCRIPTION,SUM(AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) < MONTH
AND ACCOUNT.ID = ACCOUNT_ID
AND CASH = 'Y'

union

SELECT 'PRIOR CREDIT CARD ACTIVITY' DESCRIPTION,SUM(TRANSACTION.AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT, ASSET_LIABILITY 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) < MONTH
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID
AND ACCOUNT.ASSET_LIABILITY_ID = ASSET_LIABILITY.ID
AND ASSET_LIABILITY_CLASS_ID = 1010
AND CASH = 'N'

UNION

SELECT 'PRIOR BENIFT ACTIVITY' DESCRIPTION,SUM(AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) < MONTH
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID
AND ACCOUNT.ID = 1020

UNION

SELECT 'PRIOR OTHER ACTIVITY' DESCRIPTION,SUM(TRANSACTION.AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT, ASSET_LIABILITY 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) < MONTH
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID
AND ACCOUNT.ASSET_LIABILITY_ID IS NULL
AND ASSET_LIABILITY_CLASS_ID <> 1010
AND ACCOUNT.ID <> 1020
AND CASH = 'N'

UNION

SELECT 'CURRENT CASH ACTIVITY' DESCRIPTION,SUM(AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
AND ACCOUNT.ID = ACCOUNT_ID
AND CASH = 'Y'

union

SELECT 'CURRENT CREDIT CARD ACTIVITY' DESCRIPTION,SUM(TRANSACTION.AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT, ASSET_LIABILITY 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID
AND ACCOUNT.ASSET_LIABILITY_ID = ASSET_LIABILITY.ID
AND ASSET_LIABILITY_CLASS_ID = 1010
AND CASH = 'N'

UNION

SELECT 'CURRENT BENIFT ACTIVITY' DESCRIPTION,SUM(AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
AND ACCOUNT.ID = 1020
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID

UNION

SELECT 'CURRENT OTHER ACTIVITY' DESCRIPTION,SUM(TRANSACTION.AMOUNT) AMOUNT
FROM TRANSACTION, ACCOUNT, ASSET_LIABILITY 
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = YEAR
AND EXTRACT(MONTH FROM TRANSACTION_DATE) = MONTH
AND ACCOUNT.ID = TRANSACTION.ACCOUNT_ID
AND ACCOUNT.ASSET_LIABILITY_ID IS NULL
AND ASSET_LIABILITY_CLASS_ID <> 1010
AND ACCOUNT.ID <> 1020
AND CASH = 'N';
  
END GET_SUMMARY;